## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:

# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np


# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Descriptions
0,0,Mount Isa,AU,-20.7333,139.5000,78.80,41,6,19.57,clear sky
1,1,Moose Factory,CA,51.2585,-80.6094,24.80,68,90,8.05,overcast clouds
2,2,Auki,SB,-8.7676,160.7034,84.92,70,54,2.44,broken clouds
3,3,Haileybury,CA,47.4490,-79.6373,50.00,62,90,8.05,overcast clouds
4,4,Ahmadpur East,PK,29.1431,71.2598,78.85,17,0,5.26,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
#print('Enter Minimum Temperature:')
#min_temp = input()
min_temp = float(input("What is the minimum temperature you would like for your trip? "))

#print('Enter Maximum Temperature:')
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 45
What is the maximum temperature you would like for your trip? 85

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

city_prefered_df = city_data_df.loc[(city_data_df['Max Temp'] >= min_temp) & (city_data_df['Max Temp'] <= max_temp)]
city_prefered_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Descriptions
0,0,Mount Isa,AU,-20.7333,139.5000,78.80,41,6,19.57,clear sky
2,2,Auki,SB,-8.7676,160.7034,84.92,70,54,2.44,broken clouds
3,3,Haileybury,CA,47.4490,-79.6373,50.00,62,90,8.05,overcast clouds
4,4,Ahmadpur East,PK,29.1431,71.2598,78.85,17,0,5.26,clear sky
5,5,Mahébourg,MU,-20.4081,57.7000,78.80,78,75,12.66,light rain

In [5]:
# 4a. Determine if there are any empty rows.


city_prefered_df.count()

Unnamed: 0              506
City                    506
Country                 499
Lat                     506
Lng                     506
Max Temp                506
Humidity                506
Cloudiness              506
Wind Speed              506
Current Descriptions    506
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = city_prefered_df.dropna()
clean_df.count()

Unnamed: 0              499
City                    499
Country                 499
Lat                     499
Lng                     499
Max Temp                499
Humidity                499
Cloudiness              499
Wind Speed              499
Current Descriptions    499
dtype: int64

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Descriptions", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Descriptions,Lat,Lng,Hotel Name
0,Mount Isa,AU,78.80,clear sky,-20.7333,139.5000,
2,Auki,SB,84.92,broken clouds,-8.7676,160.7034,
3,Haileybury,CA,50.00,overcast clouds,47.4490,-79.6373,
4,Ahmadpur East,PK,78.85,clear sky,29.1431,71.2598,
5,Mahébourg,MU,78.80,light rain,-20.4081,57.7000,
6,Ushuaia,AR,50.00,scattered clouds,-54.8000,-68.3000,
7,Busselton,AU,63.19,clear sky,-33.6500,115.3333,
9,Hobart,AU,55.40,broken clouds,-42.8794,147.3294,
10,Ketchikan,US,60.80,few clouds,55.3422,-131.6461,
11,Kuandian,CN,52.21,clear sky,40.7286,124.7847,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

for i,row in hotel_df.iterrows():
    #print(row[["Lat","Lng"]])

    # 6c. Get latitude and longitude from DataFrame
    Lat = row["Lat"]
    Lng = row["Lng"]
    Lat_Lng = f"{Lat},{Lng}"
    
    #print(location)
    params['location'] = Lat_Lng
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
        

    # 6e. Make request and retrieve the JSON data from the search
    response = requests.get(base_url,params).json()    
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[i,'Hotel Name'] = response['results'][0]['name']
    except (IndexError):
        print("hotel is not found skip the city")

hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city
hotel is not found skip the city

ConnectionError: HTTPSConnectionPool(host='maps.googleapis.com', port=443): Max retries exceeded with url: /maps/api/place/nearbysearch/json?radius=5000&type=lodging&key=AIzaSyAAiY1VLRvdmI-vqto6fQOdDUqUgtq4xOo&location=-8.116%2C-79.03 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000242C54624F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

In [9]:
hotel_df[hotel_df['Hotel Name'] != ''].count()

City                    286
Country                 286
Max Temp                286
Current Descriptions    286
Lat                     286
Lng                     286
Hotel Name              286
dtype: int64

In [10]:
hotel_df.count()

City                    499
Country                 499
Max Temp                499
Current Descriptions    499
Lat                     499
Lng                     499
Hotel Name              499
dtype: int64

In [11]:
# 7. Drop the rows where there is no Hotel Name.

clean_hotel_df = hotel_df[hotel_df['Hotel Name'] != '']

clean_hotel_df.head(10)

,City,Country,Max Temp,Current Descriptions,Lat,Lng,Hotel Name
0,Mount Isa,AU,78.80,clear sky,-20.7333,139.5000,ibis Styles Mt Isa Verona
2,Auki,SB,84.92,broken clouds,-8.7676,160.7034,Auki Motel
3,Haileybury,CA,50.00,overcast clouds,47.4490,-79.6373,Haileybury Beach Motel
4,Ahmadpur East,PK,78.85,clear sky,29.1431,71.2598,Irfan fabrics
5,Mahébourg,MU,78.80,light rain,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
6,Ushuaia,AR,50.00,scattered clouds,-54.8000,-68.3000,Albatros Hotel
7,Busselton,AU,63.19,clear sky,-33.6500,115.3333,Observatory Guest House
9,Hobart,AU,55.40,broken clouds,-42.8794,147.3294,Mantra on Collins Hobart
10,Ketchikan,US,60.80,few clouds,55.3422,-131.6461,Snows Cove Lodge
11,Kuandian,CN,52.21,clear sky,40.7286,124.7847,Hi Inn Dandong Kuandian Ji Xian Garden

In [12]:
# 8a. Create the output File (CSV)
output_data_file = 'WeatherPy_vacation.csv'

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [13]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [14]:
# 11a. Add a marker layer for each city to the map. 

fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))